version: '3.8'
services:
  customer_management_service:
    build: ./customers-service
    ports:
      - "7001:7001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql1:
        condition: service_healthy

  mysql1:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=customers-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin1:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin1
    links:
      - mysql1
    restart: always
    ports:
      - "5011:80"
    environment:
      - PMA_ARBITRARY=1

  payment_service:
    build: ./payment-service
    ports:
      - "7002:7002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=payments-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin2:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin2
    links:
      - mysql2
    restart: always
    ports:
      - "5012:80"
    environment:
      - PMA_ARBITRARY=1

  product_management_service:
    build: ./products-service
    ports:
      - "7003:7003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql4:
        condition: service_healthy

  order_processing_service:
    build: ./orders-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
    depends_on:
      mysql3:
        condition: service_healthy

  flower_store_service: # Aggregator service
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - customer_management_service
      - product_management_service
      - order_processing_service

  mysql3:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=order-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql4:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=products-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin3:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin3
    links:
      - mysql3
    restart: always
    ports:
      - 5015:80
    environment:
      - PMA_ARBITRARY=1

  phpmyadmin4:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin4
    links:
      - mysql4
    restart: always
    ports:
      - 5016:80
    environment:
      - PMA_ARBITRARY=1

networks:
  default:
    name: flowerstore_network