server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.example: DEBUG
spring:
  config:
    activate:
      on-profile: h2

app:
  customers-service:
    host: localhost
    port: 7001
  payments-service:
    host: localhost
    port: 7002
  products-service:
    host: localhost
    port: 7003
  orders-service:
    host: localhost
    port: 7004

---
spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

app:
  payments-service:
    host: payments-service
    port: 8080
  orders-service:
    host: orders-service
    port: 8080
  customers-service:
    host: customers-service
    port: 8080
  products-service:
    host: products-service
    port: 8080