server:
  error:
    include-message: always
  port: 7004

logging:
  level:
    root: INFO
    com.example.orderservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://mysql3/orders-db
    username: user
    password: secretpwd
    initialization-mode: always
  
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-source: metadata
              create-target: /tmp/create.sql
    hibernate:
      ddl-auto: none
  
  config:
    activate:
      on-profile: docker
  
  sql:
    init:
      platform: mysql
      mode: always
---
spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:orders-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true
  sql:
    init:
      platform: h2
      mode: always


