version: '3.8'
services:
  order_service:
    build: .
    ports:
      - "7004:7004"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql3:
        condition: service_healthy

  mysql3:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=orders-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secretpwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin3:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin3
    links:
      - mysql3
    restart: always
    ports:
      - "5014:80"
    environment:
      - PMA_ARBITRARY=1