version: '3.8'
services:
  payment_service:
    build: .
    ports:
      - "7002:7002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql2:
        condition: service_healthy

  mysql2:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=payments-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secretpwd
      - MYSQL_ROOT_PASSWORD=rootpwd
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-psecretpwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin2:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin2
    links:
      - mysql2
    restart: always
    ports:
      - "5012:80"
    environment:
      - PMA_ARBITRARY=1